apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercice-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercice-api
  template:
    metadata:
      labels:
        app: exercice-api
    spec:
      containers:
        - name: exercice-api
          image: DOCKERHUB_USERNAME/exercice-api:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: exercice-api
spec:
  selector:
    app: exercice-api
  ports:
    - port: 80
      targetPort: 80